<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="TestNgConcepts.InvocationTimeOutTest" tests="1" time="0.148" ignored="0" failures="0" timestamp="19 Oct 2021 11:54:28 GMT" skipped="0" hostname="PAKU-BLR-01" errors="1">
  <testcase name="test" time="0.148" classname="TestNgConcepts.InvocationTimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNgConcepts.InvocationTimeOutTest.test() didn&#039;t finish within the time-out 2">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNgConcepts.InvocationTimeOutTest.test() didn't finish within the time-out 2
]]>
    </error>
  </testcase> <!-- test -->
</testsuite> <!-- TestNgConcepts.InvocationTimeOutTest -->
